#
#
#

transfert:
  image: challenge-box-provider:latest
  ports:
    - "${PORT_HTTP}:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
  command: sleep 6000 #/go/bin/myapp