web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./www_site:/www_site
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
    - mysql

php:
  build: ./php/ 
  volumes:
    - ./www_site:/www_site
  links:
    - mysql

mysql:
  build: ./mysql/
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword

